akurtek_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from azbankgateways.urls import az_bank_gateways_urls
from apps.payment.views import GoToGetAwayView, CallbackGetAwayView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.movie.urls', namespace='movie'), name='movie'),
    path('user/', include('apps.user.urls', namespace='user'), name='user'),
    path('blog/', include('apps.blog.urls', namespace='blog'), name='blog'),
    path('chat/', include('apps.chat.urls', namespace='chat'), name='chat'),
    path('panel/', include('apps.panel.urls', namespace='panel'), name='panel'),
    path('notification/', include('apps.notification.urls', namespace='notification'), name='notification'),
    path('payment/', include('apps.payment.urls', namespace='payment'), name='payment'),
    path('bankgateways/', az_bank_gateways_urls()),
    path('go-to-get-away/', GoToGetAwayView.as_view()),
    path('callback-get-away/', CallbackGetAwayView.as_view()),
]

apps/payment/urls.py
from django.urls import path
from .views import *

app_name = 'payment'

urlpatterns = [
    path('', PricingPlanView.as_view(), name='index'),
    path('buy/<pk>', BuyPlanView.as_view(), name='buy'),
]

apps/payment/templates/payment/buy-plan.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <div class="iq-breadcrumb-one  iq-bg-over iq-over-dark-50"
         style="background-image: url({{ site_detail.buy_plan_background.url }});">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-sm-12">
                    <nav aria-label="breadcrumb" class="text-center iq-breadcrumb-two">
                        <h2 class="title">خرید اشتراک </h2>
                        <ol class="breadcrumb main-bg">
                            <li class="breadcrumb-item"><a href="{% url 'movie:index' %}">خانه</a></li>
                            <li class="breadcrumb-item active">خرید اشتراک</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>
    <main id="main" class="site-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-sm-12">
                    <table id="my-table" class="table" data-active="premium">
                        <thead>
                        <tr>
                            <th class="text-center iq-price-head">
                            </th>
                            <th class="text-center iq-price-head free">
                                <div class="iq-price-box">
                                    <h3 class="iq-price-rate text-white">{{ plan.price }}تومان<small>
                                        / {{ plan.period }} ماه</small></h3>

                                </div>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>

                            <th class="text-center iq-price-footer"></th>
                            <td class="text-center iq-price-footer">
                                <div class="align-items-center r-mb-23" data-animation-in="fadeInUp"
                                     data-delay-in="1.3">
                                    <a href="sign-up.html" class="btn btn-hover iq-button">انتقال به صفحه پرداخت</a>
                                </div>
                            </td>

                        </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </div>
    </main>
{% endblock %}

apps/payment/templates/payment/pricing-plan.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <!-- Header End -->
    <div class="iq-breadcrumb-one  iq-bg-over iq-over-dark-50"
         style="background-image: url({{ site_detail.pricing_plan_background.url }})">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-sm-12">
                    <nav aria-label="breadcrumb" class="text-center iq-breadcrumb-two">
                        <h2 class="title">طرح قیمت گذاری </h2>
                        <ol class="breadcrumb main-bg">
                            <li class="breadcrumb-item"><a href="{% url 'movie:index' %}">خانه</a></li>
                            <li class="breadcrumb-item active">طرح قیمت گذاری</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>

    <!-- Main container -->
    <main id="main" class="site-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-sm-12">

                    <div class="iq-pricing-card">
                        <div class="table-responsive iq-pricing pt-2">
                            <table id="my-table" class="table" data-active="premium">
                                <thead>
                                <tr>
                                    <th class="text-center iq-price-head">
                                    </th>
                                    {% for plan in pricing_plan %}
                                        <th class="text-center iq-price-head free">
                                            <div class="iq-price-box">
                                                <h3 class="iq-price-rate text-white">{{ plan.price }}تومان<small>
                                                    / {{ plan.period }} ماه</small></h3>
                                            </div>
                                        </th>
                                    {% endfor %}
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <th class="text-center iq-price-footer"></th>
                                    {% for plan in pricing_plan %}
                                        <td class="text-center iq-price-footer">
                                            <div class="align-items-center r-mb-23" data-animation-in="fadeInUp"
                                                 data-delay-in="1.3">
                                                <a href="{% url 'payment:buy' plan.id %}"
                                                   class="btn btn-hover iq-button">خرید اشتراک </a>
                                            </div>
                                        </td>
                                    {% endfor %}
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}