akurtek_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from azbankgateways.urls import az_bank_gateways_urls
from apps.payment.views import GoToGetAwayView, CallbackGetAwayView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.movie.urls', namespace='movie'), name='movie'),
    path('user/', include('apps.user.urls', namespace='user'), name='user'),
    path('blog/', include('apps.blog.urls', namespace='blog'), name='blog'),
    path('chat/', include('apps.chat.urls', namespace='chat'), name='chat'),
    path('panel/', include('apps.panel.urls', namespace='panel'), name='panel'),
    path('notification/', include('apps.notification.urls', namespace='notification'), name='notification'),
    path('payment/', include('apps.payment.urls', namespace='payment'), name='payment'),
    path('bankgateways/', az_bank_gateways_urls()),
    path('go-to-get-away/', GoToGetAwayView.as_view()),
    path('callback-get-away/', CallbackGetAwayView.as_view()),
]

apps/blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
    path('', BlogView.as_view(), name='index'),
    path('category/<category>', BlogView.as_view(), name='category'),
    path('tag/<tag>', BlogView.as_view(), name='tag')
]

apps/user/urls.py
from django.urls import path
from .views import *

app_name = 'user'

urlpatterns = [
    path('manage-profile/', ManageProfileView.as_view(), name='manage_profile'),
    path('login', LoginView.as_view(), name='login'),
    path('logout', LogOutView.as_view(), name='logout'),
    path('sign-up', SignUpView.as_view(), name='sign_up'),
    path('reset-password-send', ResetPasswordSendView.as_view(), name='reset_password_send'),
    path('reset-password/<code>', ResetPasswordView.as_view(), name='reset_password'),
    path('activation/<code>', ActivationView.as_view()),
]

apps/user/models.py
import random
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django_jalali.db import models as jmodels
from django.utils.translation import gettext_lazy as _
from django.db import models


class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """
    def create_user(self, email, fullname, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError(_("The email must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, fullname=fullname, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, fullname, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        extra_fields.setdefault("is_active", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get("is_superuser") is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(email, fullname, password, **extra_fields)


class CustomUser(PermissionsMixin, AbstractBaseUser):
    email = models.EmailField(_("email address"), blank=True, null=True, unique=True)
    fullname = models.CharField(max_length=150, default='No Name', verbose_name='نام')
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    last_login = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['fullname']

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class UserModel(CustomUser):
    is_active = models.BooleanField(default=False)
    ban = models.BooleanField(default=False)
    profile_image = models.ImageField('user/profiles', blank=True, null=True)
    register_date = jmodels.jDateTimeField(auto_now_add=True)
    birth_date = jmodels.jDateTimeField(null=True, blank=True)
    pricing = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return f'{self.email} - {self.fullname}'

apps/user/forms.py
from django import forms
from .models import *
from django.utils import timezone
from jalali_date import datetime2jalali, date2jalali


def clean_password(password, confirm_password):
    if password == confirm_password:
        if len(confirm_password) > 8 and confirm_password.isdigit() == False and confirm_password.isalpha() == False:
            return confirm_password

        else:
            return ValueError('پسورد باید شامل اعداد  و حروف و نیز بیشتر از 8 کاراکتر باشد')

    else:
        return ValueError('پسورد و تکرار آن یکی نمی باشد')

class UserForm(forms.ModelForm):

    class Meta:
        model = UserModel
        fields = ['fullname', 'profile_image', 'birth_date']

    def clean_birth_date(self):
        birth_date = self.cleaned_data['birth_date']

        if birth_date == None:
            return birth_date
        
        diff = datetime2jalali(timezone.now()).year - birth_date.year

        if 3 < diff < 130:
            return self.birth_date
        else:
            return ValueError('تاریخ صحیح نمی باشد')


class LoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())


class SignUpForm(forms.Form):
    fullname = forms.CharField(max_length=10000)
    email = forms.EmailField()
    password = forms.CharField(max_length=30, widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=30, widget=forms.PasswordInput())

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        clean_password(password, confirm_password)


class ResetPasswordSendForm(forms.Form):
    email = forms.EmailField()


class ResetPasswordForm(forms.Form):
    password = forms.CharField(max_length=30, widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=30, widget=forms.PasswordInput())

    def clean_confirm_password(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        clean_password(password, confirm_password)

apps/user/views.py
from django.shortcuts import render, HttpResponse, redirect, Http404, get_object_or_404
from django.views.generic import View
from utils.send_email import send_activation_code
from django.contrib.auth import login, logout
from django.utils.crypto import get_random_string
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.timezone import datetime
from apps.panel.models import SiteDetailModel
from redis import Redis
from .forms import *

re = Redis(host='localhost', port=6379, db=0)


class ManageProfileView(LoginRequiredMixin, View):
    def get(self, request):
        form = UserForm(instance=request.user)
        user = request.user
        if user.pricing:
            if user.pricing > datetime.now():
                pricing_amount = user.pricing - datetime.now()
            else:
                pricing_amount = None
        else:
            pricing_amount = None

        site_detail = SiteDetailModel.objects.all().first()
        context = {
            'form': form,
            'pricing_amount': pricing_amount,
            'site_detail': site_detail,
        }
        return render(request, 'user/manage-profile.html', context)

    def post(self, request):
        form = UserForm(request.POST, request.FILES)
        if form.is_valid():
            user = request.user
            cd = form.cleaned_data
            user.fullname = cd['fullname']
            user.birth_date = cd['birth_date']
            user.profile_image = cd['profile_image']
            user.save()
        return redirect('user:manage_profile')


class LoginView(View):
    def get(self, request):
        return render(request, 'user/login.html')

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = UserModel.objects.get(email=cd['email'])
            if user:
                check = user.check_password(cd['password'])
                if check:
                    login(request, user)
                    return redirect(request.META['HTTP_REFERER'])
                else:
                    return HttpResponse('پسورد اشتباه است')
            else:
                return HttpResponse('کاربر یافت نشد')


class LogOutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('movie:index')


class SignUpView(View):
    def get(self, request):
        return render(request, 'user/sign-up.html')

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = UserModel.objects.filter(email=cd['email'])
            if user.exists():

                if user.first().ban:
                    return HttpResponse('کاربر مسدود شده است')
                elif user.is_active:
                    return HttpResponse('کاربر با این مشخصات وجود دارد')
                else:
                    code = get_random_string(72)
                    request.session['user_email'] = user.email
                    re.set(f'activation_code:{user.email}', code, ex=3600)
                    send_activation_code(user.email, code)
                    return HttpResponse('برای فعال سازی خساب ایمیل خود را چک کنید')

            else:
                UserModel.objects.create_user(email=cd['email'], fullname=cd['fullname'], password=cd['password'])
                code = get_random_string(72)
                request.session['user_email'] = user.email
                re.set(f'activation_code:{user.email}', code, ex=3600)
                send_activation_code(user.email, code)
                return HttpResponse('برای فعال سازی خساب ایمیل خود را چک کنید')


class ActivationView(View):
    def get(self, request, code):
        email = request.sessin['email']
        user = get_object_or_404(UserModel, email=email)
        if user.is_active:
            return render(request, 'user/activation.html', {'message': 'کاربر قبلا فعال شده'})
        else:
            user_code = re.get(f'activation_code:{user.email}')
            if user_code == code:
                user.is_active = True
                user.save()
                return render(request, 'user/activation.html', {'message': 'کاربر فغال شد'})
            else:
                raise Http404


class ResetPasswordSendView(View):
    def get(self, request):
        return render(request, 'user/reset-password-send.html')

    def post(self, request):
        form = ResetPasswordSendForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = UserModel.objects.filter(email=cd['email'])
            if user.exists():
                if user.first().ban:
                    return HttpResponse('کاربر مسدود شده')

                else:
                    code = get_random_string(72)
                    re.set(f'reset-code:{user.email}', code, ex=3600)
                    request.session['email'] = user.email
                    send_activation_code(user.email, code)
                    return HttpResponse('code send')
            else:
                return HttpResponse('کاربر با ایمیل وجود ندارد')


class ResetPasswordView(View):
    def get(self, request, code):
        email = request.session.get('email')
        send_code = re.get(f'reset-code:{email}')
        if code == send_code:
            return render(request, 'user/reset-password.html')
        else:
            raise Http404()

    def post(self, request, code):
        form = ResetPasswordForm(request.POST)
        if form.is_valid():
            email = request.session.get('email')
            send_code = re.get(f'reset-code:{email}')
            user = UserModel.objects.filter(email).first()
            if user:
                if code == send_code:
                    cd = form.cleaned_data
                    user.set_password(cd['password'])
                    user.save()
                    return HttpResponse('پسورد تغییر یافت')

            else:
                return HttpResponse('کاربر یافت نشد')

apps/user/templates/user/activation.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <div>
        {{ message }}
    </div>
    <br><br>
    <div><a href="{% url 'movie:index' %}">بازگشت به خانه</a></div>
{% endblock %}

apps/user/templates/user/login.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <section class="sign-in-page">
        <div class="container">
            <div class="row justify-content-center align-items-center height-self-center">
                <div class="col-lg-5 col-md-12 align-self-center">
                    <div class="sign-user_card ">
                        <div class="sign-in-page-data">
                            <div class="sign-in-from w-100 m-auto">
                                <h3 class="mb-3 text-center">ورود</h3>

                                <div class="form-group">
                                    <input id="login-email" type="email" class="form-control mb-0" placeholder="ایمیل"
                                           autocomplete="off" required>
                                </div>
                                <div class="form-group">
                                    <input id="login-password" type="password" class="form-control mb-0"
                                           placeholder="رمز عبور" required>
                                </div>

                                <div class="sign-info">
                                    <button onclick="loginUser()" class="btn btn-hover">ورود</button>
                                    <div class="custom-control custom-checkbox d-inline-block">
                                        <input type="checkbox" class="custom-control-input" id="customCheck">
                                    </div>
                                </div>


                            </div>
                        </div>
                        <div id="login-message"></div>
                        <div class="mt-3">
                            <div class="d-flex justify-content-center links">
                                حساب ندارید ؟ <a href="{% url 'user:sign_up' %}" class="text-primary ml-2">ثبت نام</a>
                            </div>
                            <div class="d-flex justify-content-center links">
                                <a href="{% url 'user:reset_password_send' %}" class="f-link">رمز عبور خود را فراموش کرده اید؟</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

apps/user/templates/user/manage-profile.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <section class="m-profile manage-p">
        <div class="container h-100">
            <div class="row align-items-center justify-content-center h-100">
                <div class="col-lg-10">
                    <div class="sign-user_card">
                        <div class="row">
                            <div class="col-lg-2">
                                <div class="upload_profile d-inline-block">
                                    {% if user.profile_image %}
                                        <img src="{{ user.profile_image.url }}"
                                             class="profile-pic rounded-circle img-fluid"
                                             alt="user">
                                    {% endif %}
                                    {% if site_detail.user_non_profile_image %}
                                        <img src="{{ site_detail.user_non_profile_image.url }}"
                                             class="profile-pic rounded-circle img-fluid"
                                             alt="user">
                                    {% endif %}
                                    <div class="p-image">
                                        <i class="ri-pencil-line upload-button"></i>
                                        <input class="file-upload" type="file" accept="image/*">
                                    </div>
                                    <br><br>
                                    <div>
                                        <p>بافی مانده اشتراک</p>{{ pricing_amount }}
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-10 device-margin">
                                <div class="profile-from">
                                    <h4 class="mb-3">مدیریت نمایه</h4>
                                    <form method="post">
                                        {% csrf_token %}
                                        {% for field in form %}
                                            <div class="form-group">
                                                <label>{{ field.label }}</label>
                                                <input type="text" class="form-control mb-0" id="exampleInputl2"
                                                       placeholder="{{ field.value }}" autocomplete="off" required>
                                            </div>
                                        {% endfor %}
                                        <div class="d-flex">
                                            <button type="submit" class="btn btn-hover">ذخیره</button>
                                            <a href="{% url 'user:manage_profile' %}" class="btn btn-link">لغو</a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <div id="back-to-top">
        <a class="top" href="#top" id="top"> <i class="fa fa-angle-up"></i> </a>
    </div>



{% endblock %}

apps/user/templates/user/reset-password-send.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <!-- MainContent -->
    <section class="sign-in-page">
        <div class="container">
            <div class="row justify-content-center align-items-center height-self-center">
                <div class="col-lg-5 col-md-12 align-self-center">
                    <div class="sign-user_card ">
                        <div class="sign-in-page-data">
                            <div class="sign-in-from w-100 m-auto">
                                <h3 class="mb-3 text-center">بازنشانی رمز عبور</h3>
                                <p class="text-body">آدرس ایمیل خود را وارد کنید و ما یک ایمیل با دستورالعمل هایی برای
                                    بازنشانی گذرواژه برای شما ارسال می کنیم.</p>
                                <form class="mt-4" action="index.html">
                                    <div class="form-group">
                                        <input type="email" class="form-control mb-0" id="exampleInputEmail2"
                                               placeholder="ایمیل را وارد کنید" autocomplete="off" required>
                                    </div>
                                    <div class="sign-info">
                                        <button type="submit" class="btn btn-hover">بازنشانی</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sign in END -->
            <!-- color-customizer -->
        </div>
    </section>
{% endblock %}

apps/user/templates/user/reset-password.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <!-- MainContent -->
    <section class="sign-in-page">
        <div class="container">
            <div class="row justify-content-center align-items-center height-self-center">
                <div class="col-lg-5 col-md-12 align-self-center">
                    <div class="sign-user_card ">
                        <div class="sign-in-page-data">
                            <div class="sign-in-from w-100 m-auto">
                                <h3 class="mb-3 text-center">بازنشانی رمز عبور</h3>
                                <form class="mt-4">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>کلمه عبور</label>
                                            <input name="password" type="password" class="form-control mb-0"
                                                   id="exampleInputPassword2" placeholder="کلمه عبور" required>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label>رمز عبور را تکرار کنید</label>
                                            <input name="confirm_password" type="password" class="form-control mb-0"
                                                   id="exampleInputPassword2" placeholder="کلمه عبور" required>
                                        </div>
                                    </div>
                                    <div class="sign-info">
                                        <button type="submit" class="btn btn-hover">بازنشانی</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sign in END -->
            <!-- color-customizer -->
        </div>
    </section>
{% endblock %}

apps/user/templates/user/sign-up.html
{% extends 'parent/base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <!-- MainContent -->
    <section class="sign-in-page">
        <div class="container">
            <div class="row justify-content-center align-items-center height-self-center">
                <div class="col-lg-7 col-md-12 align-self-center">
                    <div class="sign-user_card ">
                        <div class="sign-in-page-data">
                            <div class="sign-in-from w-100 m-auto">
                                <form>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>نام کاربری</label>
                                                <input name="fullname" type="text" class="form-control mb-0" id="exampleInputEmail2"
                                                       placeholder="نام کامل را وارد کنید" autocomplete="off" required>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>ایمیل</label>
                                                <input name="email" type="email" class="form-control mb-0" id="exampleInputEmail3"
                                                       placeholder="ایمیل را وارد کنید" autocomplete="off" required>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>کلمه عبور</label>
                                                <input name="password" type="password" class="form-control mb-0"
                                                       id="exampleInputPassword2" placeholder="کلمه عبور" required>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <label>رمز عبور را تکرار کنید</label>
                                                <input name="confirm_password" type="password" class="form-control mb-0"
                                                       id="exampleInputPassword2" placeholder="کلمه عبور" required>
                                            </div>
                                        </div>

                                    </div>
                                    <button type="submit" class="btn btn-hover my-2">ثبت نام</button>

                                </form>
                            </div>
                        </div>
                        <div class="mt-3">
                            <div class="d-flex justify-content-center links">
                                قبلاً حساب کاربری دارید؟ <a href="{% url 'user:login' %}" class="text-primary ml-2">ورود</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}