akurtek_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from azbankgateways.urls import az_bank_gateways_urls
from apps.payment.views import GoToGetAwayView, CallbackGetAwayView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.movie.urls', namespace='movie'), name='movie'),
    path('user/', include('apps.user.urls', namespace='user'), name='user'),
    path('blog/', include('apps.blog.urls', namespace='blog'), name='blog'),
    path('chat/', include('apps.chat.urls', namespace='chat'), name='chat'),
    path('panel/', include('apps.panel.urls', namespace='panel'), name='panel'),
    path('notification/', include('apps.notification.urls', namespace='notification'), name='notification'),
    path('payment/', include('apps.payment.urls', namespace='payment'), name='payment'),
    path('bankgateways/', az_bank_gateways_urls()),
    path('go-to-get-away/', GoToGetAwayView.as_view()),
    path('callback-get-away/', CallbackGetAwayView.as_view()),
]

apps/movie/urls.py
from django.urls import path
from .views import *

app_name = 'movie'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('category', CategoryMainView.as_view(), name='main_category'),
    path('category/<category>', CategoryView.as_view()),
    path('privacy-policy', PrivacyView.as_view(), name='privacy'),
    path('faq', FaqView.as_view(), name='faq'),
    path('contact-us', ContactUsView.as_view(), name='contact_us'),
    path('about-us', AboutUsView.as_view(), name='about_us'),
    path('movie/<slug>', MovieBaseView.as_view(), name='movie_base'),
    path('movie-detail/<slug>', MovieDetailView.as_view(), name='movie_detail'),
    path('series/<slug>', SeriesBaseView.as_view(), name='series_base'),
    path('series-detail/<slug>', SerialDetailView.as_view(), name='series_detail'),
]

templates/partial/footer.html
{% load static %}
<footer id="contact" class="footer-one iq-bg-dark">

    <!-- Address -->
    <div class="footer-top">
        <div class="container-fluid">
            <div class="row footer-standard">
                <div class="col-lg-7">
                    <div class="widget text-left">
                        <div class="menu-footer-link-1-container">
                            <ul id="menu-footer-link-1" class="menu p-0">
                                <li id="menu-item-7314"
                                    class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7314">
                                    <a href="{% url 'movie:about_us' %}">درباره ما</a>
                                </li>
                                <li id="menu-item-7316"
                                    class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7316">
                                    <a href="{% url 'movie:privacy' %}">سیاست حفظ حریم خصوصی</a>
                                </li>
                                <li id="menu-item-7118"
                                    class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7118">
                                    <a href="{% url 'movie:faq' %}">سوالات متداول</a>
                                </li>
                                <li id="menu-item-7118"
                                    class="menu-item menu-item-type-post_type menu-item-object-page menu-item-7118">
                                    <a href="../html/watch-video.html">لیست تماشا</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    
                </div>
                <div class="col-lg-2 col-md-6 mt-4 mt-lg-0">
                    <h6 class="footer-link-title">
                        ما را دنبال کنید :
                    </h6>
                    <ul class="info-share">
                        {% if site_detail.facebook %}
                            <li><a target="_blank" href="{{ site_detail.facebook }}"><i class="fa fa-facebook"></i></a></li>
                        {% endif %}
                    {% if site_detail.twitter %}
                        <li><a target="_blank" href="{{ site_detail.twitter }}"><i class="fa fa-twitter"></i></a></li>
                    {% endif %}
                    {% if site_detail.google_plus %}
                        <li><a target="_blank" href="{{ site_detail.google_plus }}"><i class="fa fa-google-plus"></i></a></li>
                    {% endif %}
                    {% if site_detail.github %}
                        <li><a target="_blank" href="{{ site_detail.github }}"><i class="fa fa-github"></i></a></li>
                    {% endif %}
                    </ul>

                </div>
                <div class="col-lg-3 col-md-6 mt-4 mt-lg-0">
                    <div class="widget text-left">
                        <div class="textwidget">
                            <h6 class="footer-link-title">اپلیکیشن ما</h6>
                            <div class="d-flex align-items-center">
                                <a class="app-image" href="{{ site_detail.application_google_play_url }}">
                                    <img src="{{ site_detail.application_google_play_image.url }}" alt="play-store">
                                </a><br>
                                <a class="ml-3 app-image" href="{{ site_detail.application_ios_url }}"><img src="{{ site_detail.application_ios_image.url }}"
                                                                        alt="app-store"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Address END -->
</footer>